* Boopo's Escape
This is a small, simple project. You fly a spaceship from one end of the screen to the other while avoiding being shot by the turret, which can be randomly placed.
* Current progress:
A ship and turret can be rendered on the background.
* TODO [1/3]
+ [X] Determine primary data structure
+ [ ] Add the turret
+ [ ] Add turret tracking
* Data
** Pvectors
A 2-dimensional vector, (pvector Integer Integer) in (pvector x y) can represent:
- x :: the ship's velocity in the horizontal plane, or its horizontal distance from the origin
- y :: the ship's velocity in the vertical plane, or its vertical distance from the origin
** Player
Currently, a player is represented as a struct: (player Pvector Natural Pvector) in (player v r l)
- v :: A Pvector representing the ship's velocity in x- and y-coords.
- r :: [0,360] represents the rotation of the ship, where 0 is facing right and 90 is facing up. Later on, this should an accumulated value representing the heading of the ship's velocity.
- l :: A Pvector representing the location of the ship as the distance from the origin, the upper left, of the screen.
*** Notes
The controls are still a little buggy. Left and right don't determine the /heading/ of the ship's velocity, they alter the velocity itself directly. This means that pressing left and right sends you careening off in that direction, instead of just changing direction. It's kind of fun though. "Horizontal thrusters", really.
** Turret
The turret hasn't been implemented yet, here are some ideas:
- The turret tracks the players location.
- every 'R' seconds, it records the player's current location.
- After recording three such locations, it determines a best-fit linear function between the three points (such as in a scatter-plot).
- It then fires at a location f(x), taking into account the player's speed along.
